### ISSUE TITLE
Welcome to SEBC

### ISSUE THREAD

**Issue by mfernest** [sandip-dxc/SEBC#1]
Please be sure to:
* Rename this repository -- it should be `SEBC`
* Set up the labels and milestones as directed in `README.md`
* Invite @cpiva to collaborate

Close this issue once these tasks are complete and @cpiva has accepted your invitation.

**Comment by sandip-dxc** [comment]
1. Renamed the repository as SEBC
2. Changed the labels and milestones per the README.md
3. Invited @cpiva and he has accepted
